### ISSUE TITLE
suggestions and ideas

### ISSUE THREAD

**Issue by jjhesk** [wajahatkarim3/EasyMoney-Widgets#1]
adding complete supporting symbols and currency name here are the suggesting list:
SEK,SGD,THB,TRY,TWD,UAH,UYU,VND,ZAR,SAR,RUB,RON,PLN,PHP,PEN,NZD,NOK,MYR,MXN,MAD,KRW,JPY,INR,ILS,IDR,HUF,HRK,HKD,BGP,EUR,DKK,CZK,CRC,COP,CNY,CHF,CAD,BRL,BGN,AUD,ARS,AED

let the module to allow currency output to type LONG and using cent base.

**Comment by wajahatkarim3** [comment]
EasyMoney-Widgets support any kind of currency. It's not limited to those currencies which are shown in demo app. You can set currency using symbol in strings,  or passing ```Locale``` objects for any country or passing ```Currency``` objects by calling this method :

```java
moneyView.setCurrency("THD");
moneyView.setCurrency(Locale.PK);
```

Regarding cents and more small currencies, you can do it by setting currency to cent (for example), and it will give you value accordingly. 

In simple words, this library allows you to set any kind of currency to the widgets.
