### ISSUE TITLE
set right money symbol

### ISSUE THREAD

**Issue by webserveis** [wajahatkarim3/EasyMoney-Widgets#2]
Is posible set de money symbol to right side?

**Comment by wajahatkarim3** [comment]
No, at this time, it doesn't support to manually set the currency on the right side. But, if you choose any currency with right align such as Saudi Ryals etc., it will automatically align on the widgets. But, its a good idea. i will put this feature in the next version.

**Comment by paulsayed** [comment]
Is posible set the money symbol with different color?

**Comment by wajahatkarim3** [comment]
That's a good idea. Will. Work on it soon!  Thanks.

**Comment by wajahatkarim3** [comment]
It can be done using spannable strings.
