### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by SuzutsukiKagami** [wajahatkarim3/EasyMoney-Widgets#4]
if you move your selection on top(behine CurrencySymbol)
then enter point("."),it will break;
so,i temporary do this.

code:
else {
    // Some decimal number
    if (valStr.contains("."))
    {
        try {
            if (valStr.indexOf(".") == valStr.length()-1)
            {
                // decimal has been currently put
                String front = getDecoratedStringFromNumber(Long.parseLong(valStr.substring(0, valStr.length()-1)));
                setText(front + ".");
            }
            else {
                String[] nums = getValueString().split("\\.");
                String front = getDecoratedStringFromNumber(Long.parseLong(nums[0]));
                setText(front+"."+nums[1]);
            }
        }catch (Exception e){
            setText("0"+valStr);
        }
    }
}

ps:this way is not good...

**Comment by wajahatkarim3** [comment]
Thanks for the bug!!! I will look into it. Also, you can also create a pull request if you can fix the bug! Thanks

**Comment by wajahatkarim3** [comment]
Will look into later.
